### ISSUE TITLE
cmake fails under Linux

### ISSUE THREAD

**Issue by falko** [tom-r/tactics_pi#19]
I'm tried to build under Linux using the following commands:

```sh
mkdir build
cd build
cmake ..
```

and got the following error:
```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- *** Staging to build tactics_pi ***
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindwxWidgets.cmake:887 (find_package_handle_standard_args)
  cmake/PluginConfigure.cmake:54 (FIND_PACKAGE)
  CMakeLists.txt:45 (INCLUDE)
```

I already tried to install wxWidgets packages, but nothing changed. Any ideas?

**Comment by ghost** [comment]
Did you install wxWidget devel packages 3.0.X?  I ended up to download the source code of 3.0.3 and compile everything to get all the features OpenCPN requires. In fact, I ended to fork and compile the OpenCPN **first** with all its default plugins (including dashboard). There were many problems, but once resolved, tactics_pi compilation was easy (you need opencpn.lib, anyway). Compiled w/ 4.4.0 still works w/ 4.8.0. My few findings were pulled in by tom-r so you should be OK.

**Comment by falko** [comment]
@canne Thank you very much for the quick feedback. On my first try, I had installed just the packages `wx-common` and `wx3.0-headers` on my Ubuntu 16.04.3 LTS. Now I saw there is a package `libwxbase3.0-dev` and that worked. In addition, I needed to install `libwxgtk3.0-dev`, `libbz2-dev` and `zlib1g-dev` to make cmake happy.

**Comment by falko** [comment]
`make install` copied everything to `/usr/local/`. I symlinked the file to the respective `/usr/` directories so that the OpenCPN that I installed through the package manager picks up the plugin.

**Comment by tom-r** [comment]
@canne :
Thanks for helping out, much appreciated  :-)
@falko :
Sorry, I'm not a real unix nerd (although I know a bit) and I don't have a running environment ...
Reading your inital error messages I thought you hadn't set the library path at all/correctly. But missing libraries points into the same direction ... ;-)

I'm happy to read that you solved it, have fun with the plugin.
Thomas
