### ISSUE TITLE
Negative True Headings.

### ISSUE THREAD

**Issue by trudK45** [tom-r/tactics_pi#21]
When sailing close to north, say 350 degrees and you have a variation of for example  West 15 degrees you get negative true headings. Input is HDG and WMM is used to establish variation.
This error exist when having HDG or HDM as compass input.
I have modified the code and tested this and it now works as it should.
I can make a branch and commit if you want.

**Comment by tom-r** [comment]
Thanks for fixing, please give me time till the next weekend, I don't have access to my development machine right now.
BR,
Thomas

**Comment by trudK45** [comment]
If you give me push access I can make a remote branch and do a push. Only 2 files are changed tactics_pi.cpp and tactics_pi.h. You will have to change the revision I suppose.
/Hans

**Comment by trudK45** [comment]
I did a fork instead and made a pull request. #22

**Comment by rgleason** [comment]
trudik45, I would like to personally thank you for your persistence in getting this fixed for Opencpn, Dashboard and Tactics.  I realize that you are responding to several reports by users. Thank you for figuring out what was happening and providing the programming!

**Comment by rgleason** [comment]
Thanks very much Thomas, I'll  compile, test and put it up for others, with the new language files and trudK improvement.

**Comment by tom-r** [comment]
Rick.
I'll do a new patch with this change. I just had some issues compiling yesterday evening and couldn't finish.
Just wait until this is done (probably tonight).
BR,
Thomas

**Comment by rgleason** [comment]
I think we want to find these binaries  Correction: OpenCPN_buildwin.7z | 2017-12-27 | 6.2 MB
Sorry.
 at this location https://sourceforge.net/projects/opencpnplugins/files/?source=navbar

I haven't used this package, (well maybe I have) I have the binaries that were provided earlier.
Perhaps I should update?  (yes, I think I will update)  I don't believe they've changed but perhaps they have?  Pavel is a man of few words, he doesn't tell us much.

**Comment by rgleason** [comment]
I am going to update to  Correction: OpenCPN_buildwin.7z | 2017-12-27 | 6.2 MB to be sure.

**Comment by rgleason** [comment]
Unless you are having a problem.

**Comment by rgleason** [comment]
Thomas, you did it!  https://github.com/tom-r/tactics_pi/releases
Was it that "release" directory.

**Comment by rgleason** [comment]
Thomas, TransmitterDan has some changes to trudK45 improvements in Opencpn. They may apply too Tactics too.

See

https://github.com/OpenCPN/OpenCPN/commit/c4fb6a0ad0205501ae902b57f9c64b7d0262a199
https://github.com/OpenCPN/OpenCPN/issues/1024

**Comment by rgleason** [comment]
I think this can now be closed. .. Is that correct?

**Comment by tom-r** [comment]
Hi Rick,
yes it can be closed.
I still had trudK45's code in tactics, and transmitterdans code is exactly the same functionality, just a bit more "elegant" ...
So I changed it manually to transmitterdans code (local "heading" variable).
It'll come with the next patch, I'm reworking some code on the same file right now, which is not yet ready for a push to github ...
Thomas

**Comment by rgleason** [comment]
Thanks so much. Thomas.
