### ISSUE TITLE
tdan optimizations, canne and tom-r repos

### ISSUE THREAD

**Issue by rgleason** [tom-r/tactics_pi#32]
Dear Thomas,
Your most recent 6 commits have been merged into my repo master branch.

I notice that several of the commits change/revert the work TDan did to improve and optimize performance ( cpu & memory).  Will these change significantly now?

Note my master = tom-r
My ov50= canne's work.
At some point these should come together I think, (hopefully)

**Comment by tom-r** [comment]
Rick,
there was a bug in transmitterdans code, with his fix there were NO vertical timelines anymore at all for all of the instruments he "optimized" ;-).
Being  out sailing, I decided to revert back to a working status first  to give anyone downloading the source code a chance for a running system and then look into the code without a hassle and fix it (not knowing when I have time out there).
His improvements are already back in tactics **_with_** the bugfix, my commit was "performance improvements reimplemented with bugfix".
Petri already knows about this.
Thomas

**Comment by rgleason** [comment]
Thanks,  I guess that would optimize cpu & memory at the expense of useability. His intent is preserved.
