### ISSUE TITLE
Minor document correction request - polar loading procedure

### ISSUE THREAD

**Issue by ghost** [tom-r/tactics_pi#35]
Related to https://github.com/tom-r/tactics_pi/commit/d95196cddfa7611987d742ca8ac9b039aee31f23 - can you please consider to correct the procedure explained in the documentation:
from

> Loading Procedure :
> 1. The whole array is prefilled with NAN values.
> 

to

> Loading Procedure :
> 1.The TWA = 0 row and the TWS = 0 column is filled with zeros 
> 2 The rest of the array is filled with NAN values.

This would - at least - help a tester who is not the developer:: he or she can check the lookup table output to see that the averaged values are not NANs (they have been calculated) and that they indeed start from 0.0.

**Comment by tom-r** [comment]
Done, documentation updated.
