### ISSUE TITLE
Project description missing

### ISSUE THREAD

**Issue by SamsonovAnton** [tom-r/tactics_pi#4]
It would be nice to cover the purpose of this plugin in `README.md` and also provide a short description of the repository.

**Comment by tom-r** [comment]
Anton,

next to README.md you find the detailed documentation in tactics_pi.odt and tactics_pi,pdf.
I mentioned both in README.md now.

Thomas

**Comment by SamsonovAnton** [comment]
> You find the detailed documentation in tactics_pi.odt and tactics_pi,pdf. I mentioned both in README.md now.

That is all fine, but I meant that the entire introductory part of `tactics_pi.pdf` should be copied to `README.md` prologue, — so that people know _**why**_ should they be interested in this plugin in the first place. A brief summary would also be great as a project description here on GitHub, instead that default “No description or website provided” message.

**Comment by tom-r** [comment]
Anton,

I updated README.md and poject description

Thomas
