### ISSUE TITLE
The SVG icon is missin in Journeyman tools style

### ISSUE THREAD

**Issue by Hakansv** [tom-r/tactics_pi#6]
The icon is nice in traditional style but has to be adapted also to Journeyman. See attached pictures:
Unfortunately I've no advice how to do this but most of the other plugins are now working.

![rw-svg icon journeyman](https://cloud.githubusercontent.com/assets/7202854/16807498/f605ab28-4918-11e6-926a-6aada6f8942c.PNG)
![rw-svg icon traditional](https://cloud.githubusercontent.com/assets/7202854/16807499/f60c79b2-4918-11e6-9017-70aad4ab6589.PNG)

**Comment by tom-r** [comment]
Hakan,
I'm underway sailing till 24.th of July. I will come back to you after my return
Thomas

**Comment by tom-r** [comment]
Hakan,
I added the standard icon to the github code for Journeyman styles.
Thomas

**Comment by Hakansv** [comment]
Thomas
Thanks, as nice as the trad. one.
BTW Please give a note when you're ready for latest language updates. Some more are performed since last push, but French is not completed. I think his out sailing. (As me for the very moment.) Use: momo at stupan.se
Håkan
