### ISSUE TITLE
Building the plugin notes

### ISSUE THREAD

**Issue by rgleason** [tom-r/tactics_pi#8]
Tom, after looking at the readme.md which looks very good. I don't know if this is important or not, but what I do to build is

Build as normally:

```
cd ..
cd build
cmake  -T v120_xp ..
cmake --build . --config release
cpack
```

Note the double periods in the first cmake 
and the single period in the second cmake.
The cpack requires NSIS to make an executable.

You can close this if you'd like

**Comment by tom-r** [comment]
Thanks Rick, README.md is updated
